### ISSUE TITLE
Data loss in sink node

### ISSUE THREAD

**Issue by overvenus** [pingcap/ticdc#2632]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do? If possible, provide a recipe for reproducing the error.

Run TiCDC with 80GB incremental data. Sink flush events do not match puller received events.
![image](https://user-images.githubusercontent.com/2150711/130786830-dfa4d308-8359-481b-a54b-cbb03e001893.png)

It's caused by checking `event.Row` without wait `event.WaitPrepare()`, `Row` is not ready to use.

https://github.com/pingcap/ticdc/blob/2cde64188a1483ae90859612d6d5c62d27513c89/cdc/processor/pipeline/sink.go#L151-L154

4. Versions of the cluster

TiCDC v4.0.x

**Comment by hi-rustin** [comment]
Root cause:
1. we are actually using not v5.1.2, but kvclient v2 and new owner/processor enabled on the release-4.0 version.
2. The real reason for the lack of WaitPrepare is that we lost the mounter change in the https://github.com/pingcap/ticdc/pull/2091 PR, so we didn't do the WaitPrepare correctly, and we happened to use the row value in the https://github.com/pingcap/ticdc/pull/2271 PR in advance. This is the reason for the problem.

Actions:

- [ ] @liuzix will help fix issues with release 4.0 and could-cdc-4.0
- [ ] @hi-rustin I will help clean up that [useless call](https://github.com/pingcap/ticdc/blob/200d87785ed5f14aebc5f72d6e5ab2ab5ba70f4f/cdc/processor/pipeline/sink.go#L254). Because mounter will make sure the row is ready.


Thank you all so much for your help! ❤️

**Comment by overvenus** [comment]
This issue only affects the cloud-cdc-4.0 branch, closed.
