### ISSUE TITLE
does ticdc support synchronization data from v4.0.2 to v5.2.1？

### ISSUE THREAD

**Issue by lddlww** [pingcap/ticdc#3305]
### Before asking a question, make sure you have

- [X] Searched existing Stack Overflow questions
- [X] Googled your question
- [X] Searched open and closed [GitHub issues](https://github.com/pingcap/ticdc/issues?q=is%3Aissue)
- [X] Read the [documentation](https://docs.pingcap.com/tidb/stable)

### What is your question?

does ticdc support synchronization data from v4.0.2 to v5.2.1？

**Comment by amyangfei** [comment]
- TiCDC support to replicate data from v4.0.x TiDB cluster to v5.2.1, but TiCDC must keep the same version with upstream TiDB, which means we should use the `v4.0.x` TiCDC.
- Besides TiCDC is released sine v4.0.6, before this version, we don't recommend to use TiCDC because the old version is not stable and protocol between TiKV and TiCDC has changed after GA.

**Comment by lddlww** [comment]
oh，thanks for reply

i got it risky，and i am closing this issue now

**Comment by amyangfei** [comment]
4.0 TiDB can still use https://github.com/pingcap/tidb-binlog

**Comment by lddlww** [comment]
saddly，the binlog was closed in my ```product tidb cluster```
